apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: goserver
  newName: allysfilho/gitopsfc
  newTag: a1fb420bc4da25c05e49a86bd46a407d26fa2a00
