apiVersion: apps/v1
kind: Deployment
metadata:
  name: "goserver"
  labels:
    app: goserver
spec:
  selector:
    matchLabels:
      app: goserver
  replicas: 1
  template:
    metadata:
      labels:
        app: goserver
    spec:
      containers:
        - name: goserver
          image: "allysfilho/hello-go:v5"
# HPA
          resources:
            requests:
              cpu: "0.05"
              memory: 20Mi
            limits:
              cpu: "0.05"
              memory: 25Mi
# Probes
          startupProbe:
            httpGet:
              path: /healthz
              port: 8000
            periodSeconds: 3
            failureThreshold: 1
            initialDelaySeconds: 10

          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            periodSeconds: 3
            failureThreshold: 1
            # initialDelaySeconds: 10

          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            periodSeconds: 5
            failureThreshold: 1
            timeoutSeconds: 1
            successThreshold: 1
            # initialDelaySeconds: 15

# ConfigMap and Secret
          envFrom:
            - configMapRef:
                name: goserver-env
            - secretRef:
                name: goserver-secret
            
          volumeMounts:
            - mountPath: "/go/myfamily"
              name: config
              readOnly: true
            - mountPath: "/go/pvc"
              name: goserver-volume
# Volumes
      volumes:
        - name: "goserver-volume"
          persistentVolumeClaim:
            claimName: "goserver-pvc"
        - name: config
          configMap:
            name: configmap-family
            items:
              - key: members
                path: family.txt